// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlzikbwmaufvmuvlnwmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsemlrYndtYXVmdm11dmxud21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3OTEzMjQsImV4cCI6MjA3ODM2NzMyNH0.xHIFBkUHjnT-4ITfc5X9p_58f42URfGIAkyvfc0unRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});